### ISSUE TITLE
Bug: eleventy-plugin-styles: Creates page folders which conflict with page .html files

### ISSUE THREAD

**Issue by seangwright** [Halo-Lab/eleventy-packages#9]
For some reason, my site is creating folders for pages but then failing to create the pages because the names of the html files generated for the pages conflicts with the folders created by this plugin:

![image](https://user-images.githubusercontent.com/1382768/159175756-31595f06-21de-4427-b2d3-811f3e2c867e.png)

Here's my config

```js
const { styles } = require('eleventy-plugin-styles');

module.exports = function (eleventyConfig) {
  // Site title
  eleventyConfig.addGlobalData('siteTitle', '...');

  // Add plugins
  eleventyConfig.addPlugin(styles, {
    inputDirectory: 'src/styles',
    publicDirectory: 'styles',
  });

  // ..

  return {
    dir: {
      input: 'src',
      output: '_site',
      includes: 'includes',
      layouts: 'layouts',
      data: 'data',
    },
    templateFormats: ['njk', 'md'],
    htmlTemplateEngine: 'njk',
    markdownTemplateEngine: 'njk',
  };
```

I created a minimal reproduction

<https://github.com/seangwright/eleventy-plugin-styles-path-error>

**Comment by Kapelianovych** [comment]
Hi! Sorry for the late answer and fix. It turned out that Eleventy uses the `/` character as a path delimiter even on Windows. It is fixed in [1.4.3](https://www.npmjs.com/package/eleventy-plugin-styles). Thanks for contribution!
